version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.9-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npx webpack
      - run: npx jest spec/e2e.spec.ts
